acsadmin/urls.py
from django.urls import path

import acsadmin.views

app_name = 'acsadmin'

urlpatterns = [
    path('http/requests/', acsadmin.views.AcsHttpRequestList.as_view(), name='acs_http_request_list'),
    path('http/requests/<int:pk>/', acsadmin.views.AcsHttpRequestDetail.as_view(), name='acs_http_request_detail'),

    path('http/responses/', acsadmin.views.AcsHttpResponseList.as_view(), name='acs_http_response_list'),
    path('http/responses/<int:pk>/', acsadmin.views.AcsHttpResponseDetail.as_view(), name='acs_http_response_detail'),

    path('sessions/', acsadmin.views.AcsSessionList.as_view(), name='acs_session_list'),
    path('sessions/failed/', acsadmin.views.AcsSessionList.as_view(), name='acs_session_list_failed', kwargs={'only_failed': True}),
    path('sessions/verifiedfailed/', acsadmin.views.AcsSessionList.as_view(), name='acs_session_list_failed_verified', kwargs={'only_failed': True, 'only_verified': True}),
    path('sessions/<int:pk>/', acsadmin.views.AcsSessionDetail.as_view(), name='acs_session_detail'),

    path('jobqueue/', acsadmin.views.AcsQueueJobList.as_view(), name='acs_queue_job_list'),
    path('jobqueue/hideautomatic/', acsadmin.views.AcsQueueJobList.as_view(), name='acs_queue_job_list_hideautomatic', kwargs={'hideautomatic': True}),
    path('jobqueue/<int:pk>/', acsadmin.views.AcsQueueJobDetail.as_view(), name='acs_queue_job_detail'),

    path('devicemodels/', acsadmin.views.AcsDeviceModelList.as_view(), name='acs_device_model_list'),
    path('devicemodels/<int:pk>/', acsadmin.views.AcsDeviceModelDetail.as_view(), name='acs_device_model_detail'),

    path('devicecategories/', acsadmin.views.AcsDeviceCategoryList.as_view(), name='acs_device_category_list'),
    path('devicecategories/<int:pk>/', acsadmin.views.AcsDeviceCategoryDetail.as_view(), name='acs_device_category_detail'),

    path('devicevendors/', acsadmin.views.AcsDeviceVendorList.as_view(), name='acs_device_vendor_list'),
    path('devicevendors/<int:pk>/', acsadmin.views.AcsDeviceVendorDetail.as_view(), name='acs_device_vendor_detail'),

    path('devices/', acsadmin.views.AcsDeviceList.as_view(), name='acs_device_list'),
    path('devices/<int:pk>/', acsadmin.views.AcsDeviceDetail.as_view(), name='acs_device_detail'),
    path('devices/<int:pk>/create_job/', acsadmin.views.AcsQueueJobCreate.as_view(), name='acs_queue_job_create'),
    path('devices/<int:pk>/allacssessions/', acsadmin.views.AllAcsSessions.as_view(), name='acsdevice_all_acs_sessions'),
]

acsadmin/forms.py
from django import forms
from django.conf import settings
from defusedxml.lxml import fromstring
from django.core.exceptions import ValidationError

class AcsDeviceActionForm(forms.Form):
    action = forms.ChoiceField(
        widget=forms.RadioSelect,
        choices=[(x, x) for x in settings.CWMP_CPE_VALID_RPC_METHODS]
    )

    xml = forms.CharField(
        widget=forms.Textarea,
        label="XML payload",
        help_text="Optionally (when needed) input the XML payload of the RPC call.",
        required=False
    )

    reason = forms.CharField(
        label="Reason",
        help_text="Please specify the reason why you are adding this ACS RPC call",
    )

    urgent = forms.BooleanField(
        label="Urgent?",
        help_text='Check to make this job urgent. Leave unchecked to wait until next inform.',
        required=False
    )

    def clean(self):
        cleaned_data = super(AcsDeviceActionForm, self).clean()
        errorlist = []
        if cleaned_data['xml']:
            try:
                # fromstring takes bytes, so convert the string from our form to bytes, utf-8 encoded of course
                xmlroot = fromstring(cleaned_data['xml'].encode('utf-8'))
            except Exception as E:
                errorlist.append(ValidationError('XML not valid: %s' % E, code='invalid_xml'))

        # any errors to report?
        if errorlist:
            raise ValidationError(errorlist)

        return cleaned_data

acsadmin/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import FormView, CreateView
from django.shortcuts import get_object_or_404

from acs.models import *
from .forms import AcsDeviceActionForm


class AcsQueueJobList(ListView):
    model = AcsQueueJob
    template_name = 'acs_queue_job_list.html'
    paginate_by = 25

    def get_queryset(self):
        queryset = super(AcsQueueJobList, self).get_queryset()
        if 'hideautomatic' in self.kwargs and self.kwargs['hideautomatic']:
            queryset = queryset.exclude(automatic=True)
        return queryset


class AcsQueueJobDetail(DetailView):
    model = AcsQueueJob
    template_name = 'acs_queue_job_detail.html'


class AcsQueueJobCreate(CreateView):
    model = AcsQueueJob
    template_name = 'acs_queue_job_create.html'
    fields = ['cwmp_rpc_object_xml', 'reason', 'urgent']

    def setup(self, *args, **kwargs):
        super().setup(*args, **kwargs)
        self.acs_device = get_object_or_404(
            AcsDevice,
            pk=kwargs['pk'],
        )

    def form_valid(self, form):
        job = form.save(commit=False)
        job.acs_device = self.acs_device
        job.save()
        return(super().form_valid(form))


class AcsSessionList(ListView):
    model = AcsSession
    template_name = 'acs_session_list.html'
    paginate_by = 25

    def get_queryset(self):
        queryset = super(AcsSessionList, self).get_queryset()
        #queryset = queryset.get_related()
        if 'only_failed' in self.kwargs and self.kwargs['only_failed']:
            queryset = queryset.filter(session_result=False)
        if 'only_verified' in self.kwargs and self.kwargs['only_verified']:
            queryset = queryset.filter(client_ip_verified=True)
        return queryset


class AcsSessionDetail(DetailView):
    model = AcsSession
    template_name = 'acs_session_detail.html'


class AcsHttpRequestList(ListView):
    model = AcsHttpRequest
    template_name = 'acs_http_request_list.html'
    paginate_by = 25


class AcsHttpRequestDetail(DetailView):
    model = AcsHttpRequest
    template_name = 'acs_http_request_detail.html'


class AcsHttpResponseList(ListView):
    model = AcsHttpResponse
    template_name = 'acs_http_response_list.html'
    paginate_by = 25


class AcsHttpResponseDetail(DetailView):
    model = AcsHttpResponse
    template_name = 'acs_http_response_detail.html'


class AcsDeviceModelList(ListView):
    model = AcsDeviceModel
    template_name = 'acs_device_model_list.html'
    paginate_by = 25


class AcsDeviceModelDetail(DetailView):
    model = AcsDeviceModel
    template_name = 'acs_device_model_detail.html'


class AcsDeviceCategoryList(ListView):
    model = AcsDeviceCategory
    template_name = 'acs_device_category_list.html'
    paginate_by = 25


class AcsDeviceCategoryDetail(DetailView):
    model = AcsDeviceCategory
    template_name = 'acs_device_category_detail.html'


class AcsDeviceVendorList(ListView):
    model = AcsDeviceVendor
    template_name = 'acs_device_vendor_list.html'
    paginate_by = 25


class AcsDeviceVendorDetail(DetailView):
    model = AcsDeviceVendor
    template_name = 'acs_device_vendor_detail.html'


class AcsDeviceList(ListView):
    model = AcsDevice
    template_name = 'acs_device_list.html'
    paginate_by = 25


class AcsDeviceDetail(DetailView):
    model = AcsDevice
    template_name = 'acs_device_detail.html'


class AllAcsSessions(ListView):
    model = AcsSession
    template_name = 'acs_session_list.html'
    paginate_by = 100

    def get_queryset(self):
        return AcsSession.objects.filter(acs_device_id=self.kwargs['pk'])

acsadmin/templates/acs_device_category_detail.html
{% extends "base.html" %}
{% block head_title %}{{ object }}{% endblock head_title %}
{% block content %}
    {% include 'includes/acs_device_category_detail_panel.html' with acs_device_category=object %}
    {% include 'includes/acs_device_model_list_panel.html' with acs_device_model_list=object.acsdevicemodels.all headline='ACS Device Models Under This Category' %}
{% endblock content %}

acsadmin/templates/acs_device_category_list.html
{% extends "base.html" %}
{% block head_title %}ACS Device Categories{% endblock head_title %}
{% block content %}
    {% include 'includes/acs_device_category_list_panel.html' with acs_device_category_list=object_list %}
{% endblock content %}

acsadmin/templates/acs_queue_job_detail.html
{% extends "base.html" %}
{% block head_title %}{{ object }}{% endblock head_title %}
{% block content %}
    {% include 'includes/acs_queue_job_detail_panel.html' with aqj=object %}
{% endblock content %}

acsadmin/templates/includes/acs_device_category_list_panel.html
{% load custom_template_filters %}
{% include 'includes/collapsable-panel-header.html' with name='AcsDeviceCategoryList' headline=headline|default:"ACS Device Category List" %}
        {% if acs_device_category_list %}
            {% if is_paginated %}
                {% include 'includes/pagination-footer.html' %}
            {% endif %}
            <table class="table">
                <thead>
                    <tr>
                        <th>ACS Device Category</th>
                        <th>Name</th>
                        <th>Models</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                {% for acs_device_category in acs_device_category_list %}
                    {% url 'acsadmin:acs_device_category_detail' pk=acs_device_category.id as acs_device_category_detail_url %}
                    <tr>
                        <td>{% include 'includes/small-details-button.html' with url=acs_device_category_detail_url %}{{ acs_device_category.tag }}</td>
                        <td>{{ acs_device_category.name }}</td>
                        <td><span class="badge">{{ acs_device_category.acsdevicemodels.count }}</span></td>
                        <td>
                            {% include 'includes/details-button.html' with url=acs_device_category_detail_url %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            {% if is_paginated %}
                {% include 'includes/pagination-footer.html' %}
            {% endif %}
        {% else %}
            <p>No Acs Device Categories found!</p>
        {% endif %}
{% include 'includes/collapsable-panel-footer.html' %}

acsadmin/templates/includes/acs_device_detail_panel.html
{% load custom_template_filters %}
<div class="panel panel-info">
    <div class="panel-heading"><h4>{{ headline|default:"ACS Device Details for "|addstr:acs_device.tag }}</h4></div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-9">
                {% url 'acsadmin:acs_device_detail' pk=acs_device.id as acs_device_detail_url %}
                {% url 'acsadmin:acs_device_vendor_detail' pk=acs_device.model.vendor.id as acs_device_vendor_detail_url %}
                {% url 'acsadmin:acs_device_model_detail' pk=acs_device.model.id as acs_device_model_detail_url %}
                <table class="table table-bordered">
                    <tr>
                        <th style="text-align: right">ACS Device</th>
                        <td>{% include 'includes/small-details-button.html' with url=acs_device_detail_url %} {{ acs_device }}</td>
                    </tr>
                    <tr>
                        <th style="text-align: right">Vendor</th>
                        <td>{% include 'includes/small-details-button.html' with url=acs_device_vendor_detail_url %} {{ acs_device.model.vendor }}</td>
                    </tr>
                    <tr>
                        <th style="text-align: right">Model</th>
                        <td>{% include 'includes/small-details-button.html' with url=acs_device_type_detail_url %} {{ acs_device.model }}</td>
                    </tr>
                    <tr>
                        <th style="text-align: right">Serial</th>
                        <td>{{ acs_device.serial }}</td>
                    </tr>
                    <tr>
                        <th style="text-align: right">Related Device</th>
                        <td>{% include 'includes/small-details-button.html' with url=acs_device.get_related_device.get_absolute_url %}{{ acs_device.get_related_device }}</td>
                    </tr>
                    <tr>
                        <th style="text-align: right">Latest Inform</th>
                        <td>{{ acs_device.acs_latest_inform | default:"N/A" }}</td>
                    </tr>
                    <tr>
                        <th style="text-align: right">Latest Inform Result</th>
                        <td>{{ acs_device.acs_latest_session_result }}</td>
                    </tr>
                    <tr>
                        <th style="text-align: right">Number of Informs</th>
                        <td>{{ acs_device.acs_inform_count }}</td>
                    </tr>
                    <tr>
                        <th style="text-align: right">Current Config Level</th>
                        <td>{{ acs_device.current_config_level | default:"N/A" }}</td>
                    </tr>
                    <tr>
                        <th style="text-align: right">Desired Config Level</th>
                        <td>{{ acs_device.get_desired_config_level | default:"N/A" }} {% if acs_device.desired_config_level %}(LOCAL OVERRIDE){% endif %}</td>
                    </tr>
                    <tr>
                        <th style="text-align: right">Current Software Version</th>
                        <td>{{ acs_device.current_software_version | default:"N/A" }}</td>
                    </tr>
                    <tr>
                        <th style="text-align: right">Desired Software Version</th>
                        <td>{{ acs_device.get_desired_software_version | default:"N/A" }} {% if acs_device.desired_software_version %}(LOCAL OVERRIDE){% endif %}</td>
                    </tr>
                </table>
            </div>
            <div class="col-md-3">
                <div class="panel">
                    <div class="panel-body">
                        {% url 'acsadmin:acs_queue_job_create' pk=acs_device.id as acs_queue_job_create_url %}
                        <p>{% include 'includes/create-button.html' with url=acs_queue_job_create_url buttontext='Schedule ACS RPC Job' %}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% include 'includes/detail_panel_footer.html' %}
</div>

acsadmin/templates/includes/acs_device_list_panel.html
{% load custom_template_filters %}
{% include 'includes/collapsable-panel-header.html' with name='AcsDeviceList' headline=headline|default:"ACS Device List" %}
    {% if acs_device_list %}
        {% if is_paginated %}
            {% include 'includes/pagination-footer.html' %}
        {% endif %}
        <table class="table">
            <thead>
                <tr>
                    <th>ACS Device</th>
                    <th>Model</th>
                    <th>Vendor</th>
                    <th>Serial</th>
                    <th>Related Device</th>
                    <th>Inform</th>
                    <th>Informs</th>
                    <th>Config Level</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
            {% for ad in acs_device_list %}
                {% url 'acsadmin:acs_device_detail' pk=ad.id as acsdevice_detail_url %}
                {% url 'acsadmin:acs_device_model_detail' pk=ad.model.id as acsdevicemodel_detail_url %}
                {% url 'acsadmin:acs_device_vendor_detail' pk=ad.model.vendor.id as acsdevicvendor_detail_url %}
                <tr>
                    <td>{% include 'includes/small-details-button.html' with url=acsdevice_detail_url %}{{ ad.tag }}</td>
        <td>{% include 'includes/small-details-button.html' with url=acsdevicemodel_detail_url %}{{ ad.model }}</td>
        <td>{% include 'includes/small-details-button.html' with url=acsdevicevendor_detail_url %}{{ ad.model.vendor }}</td>
                    <td>{{ ad.serial }}</td>
        <td>{% if ad.get_related_device %}
            {% include 'includes/small-details-button.html' with url=ad.get_related_device.get_absolute_url %}{{ ad.get_related_device }}
            {% else %}
                N/A
            {% endif %}
        </td>
                    <td>{{ ad.acs_latest_inform }} {{ ad.acs_latest_session_result|truefalseicon|safe }}</td>
                    <td><span class="badge">{{ ad.acs_inform_count }}</span></td>
                    <td>{{ ad.current_config_level }}{% if ad.desired_config_level %}<span class="danger">(desired: {{ ad.desired_config_level }})</span>{% endif %}</td>
                    <td>
                        {% include 'includes/details-button.html' with url=acsdevice_detail_url %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {% if is_paginated %}
            {% include 'includes/pagination-footer.html' %}
        {% endif %}
    {% else %}
        <p>No acs devices found!</p>
    {% endif %}
{% include 'includes/collapsable-panel-footer.html' %}

acsadmin/templates/includes/acs_device_model_detail_panel.html
{% load custom_template_filters %}
<div class="panel panel-info">
    <div class="panel-heading"><h4>{{ headline|default:"ACS Device Model Details for "|addstr:acs_device_model.tag }}</h4></div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-9">
                {% url 'acsadmin:acs_device_model_detail' pk=acs_device_model.id as acs_device_model_detail_url %}
                {% url 'acsadmin:acs_device_vendor_detail' pk=acs_device_model.vendor.id as acs_device_vendor_detail_url %}
                {% url 'acsadmin:acs_device_category_detail' pk=acs_device_model.category.id as acs_device_category_detail_url %}
                <table class="table table-bordered">
                    <tr>
                        <th style="text-align: right">ACS Device Model</th>
                        <td>{% include 'includes/small-details-button.html' with url=acs_device_model_detail_url %} {{ acs_device_model.tag }}</td>
                    </tr>
                    <tr>
                        <th style="text-align: right">Name</th>
                        <td>{{ acs_device_model.name }}</td>
                    </tr>
                    <tr>
                        <th style="text-align: right">Vendor</th>
                        <td>{% include 'includes/small-details-button.html' with url=acs_device_vendor_detail_url %} {{ acs_device_model.vendor }}</td>
                    </tr>
                    <tr>
                        <th style="text-align: right">Device Category</th>
                        <td>{% include 'includes/small-details-button.html' with url=acs_device_category_detail_url %} {{ acs_device_model.category }}</td>
                    </tr>
                    <tr>
                        <th style="text-align: right">Desired Config Level</th>
                        <td>{{ acs_device_model.desired_config_level|default:"N/A" }}</td>
                    </tr>
                    <tr>
                        <th style="text-align: right">Desired Software Version</th>
                        <td>{{ acs_device_model.desired_software_version|default:"N/A" }}</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    {% include 'includes/detail_panel_footer.html' %}
</div>

acsadmin/templates/includes/acs_device_model_list_panel.html
{% load custom_template_filters %}
{% include 'includes/collapsable-panel-header.html' with name='AcsDeviceModelList' headline=headline|default:"ACS Device Model List" %}
        {% if acs_device_model_list %}
            {% if is_paginated %}
                {% include 'includes/pagination-footer.html' %}
            {% endif %}
            <table class="table">
                <thead>
                    <tr>
                        <th>ACS Device Model</th>
                        <th>Name</th>
                        <th>Vendor</th>
                        <th>Category</th>
                        <th>Desired Config Level</th>
                        <th>Desired Software Version</th>
                        <th>Devices</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                {% for acs_device_model in acs_device_model_list %}
                    {% url 'acsadmin:acs_device_model_detail' pk=acs_device_model.id as acs_device_model_detail_url %}
                    {% url 'acsadmin:acs_device_vendor_detail' pk=acs_device_model.vendor.id as acs_device_vendor_detail_url %}
                    {% url 'acsadmin:acs_device_category_detail' pk=acs_device_model.category.id as acs_device_category_detail_url %}
                    <tr>
                        <td>{% include 'includes/small-details-button.html' with url=acs_device_model_detail_url %}{{ acs_device_model.tag }}</td>
                        <td>{{ acs_device_model.name }}</td>
                        <td>{% include 'includes/small-details-button.html' with url=acs_device_vendor_detail_url %}{{ acs_device_model.vendor }}</td>
                        <td>{% include 'includes/small-details-button.html' with url=acs_device_category_detail_url %}{{ acs_device_model.category }}</td>
                        <td>{{ acs_device_model.desired_config_level|default:"N/A" }}</td>
                        <td>{{ acs_device_model.desired_software_version|default:"N/A" }}</td>
                        <td><span class="badge">{{ acs_device_model.acsdevices.count }}</span></td>
                        <td>
                            {% include 'includes/details-button.html' with url=acs_device_model_detail_url %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            {% if is_paginated %}
                {% include 'includes/pagination-footer.html' %}
            {% endif %}
        {% else %}
            <p>No Acs Device Models found!</p>
        {% endif %}
{% include 'includes/collapsable-panel-footer.html' %}

acsadmin/templates/includes/acs_http_conversation_panel.html
{% load custom_template_filters %}
{% include 'includes/collapsable-panel-header.html' with name='AcsHttpConversation' headline=headline|default:"ACS HTTP Conversation" %}
        {% if acs_http_conversationlist %}
            {% if is_paginated %}
                {% include 'includes/pagination-footer.html' %}
            {% endif %}
            <table class="table">
                <thead>
                    <tr>
                        <th>Reqresp</th>
                        <th>Direction</th>
                        <th>When</th>
                        <th>RPC Method</th>
                        <th class='text-center'>Headers</th>
                        <th class='text-center'>Body</th>
                        <th>RPC Response To</th>
                        <th>RPC Response</th>
                        <th>ACS Queue Job</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                {% for acs_http in acs_http_conversationlist %}
                    <tr>
                        {% if acs_http.is_request %}
                          {% url 'acsadmin:acs_http_request_detail' pk=acs_http.id as acs_http_detail_url %}
                          {% if acs_http.rpc_response_to %}
                            {% url 'acsadmin:acs_http_response_detail' pk=acs_http.rpc_response_to.id as response_to_detail_url %}
                          {% endif %}
                          {% if acs_http.rpc_response %}
                            {% url 'acsadmin:acs_http_response_detail' pk=acs_http.rpc_response.id as rpc_response_detail_url %}
                          {% endif %}
                        {% else %}
                          {% url 'acsadmin:acs_http_response_detail' pk=acs_http.id as acs_http_detail_url %}
                          {% if acs_http.rpc_response_to %}
                            {% url 'acsadmin:acs_http_request_detail' pk=acs_http.rpc_response_to.id as response_to_detail_url %}
                          {% endif %}
                          {% if acs_http.rpc_response %}
                            {% url 'acsadmin:acs_http_request_detail' pk=acs_http.rpc_response.id as rpc_response_detail_url %}
                          {% endif %}
                          {% if acs_http.queuejob %}
                            {% url 'acsadmin:acs_queue_job_detail' pk=acs_http.queuejob.id as queue_job_detail_url %}
                          {% endif %}
                        {% endif %}
                        <td>
                          {% include 'includes/small-details-button.html' with url=acs_http_detail_url %}{{ acs_http }}
                        </td>
                        <td>
                          {% if acs_http.is_request %}
                            <i class="fa fa-share" aria-hidden="true"></i> HTTP Request
                          {% else %}
                            <i class="fa fa-reply" aria-hidden="true"></i> HTTP response
                          {% endif %}
                        </td>
                        <td>{{ acs_http.created_date }}</td>
                        <td>{{ acs_http.soap_element_ns }}</td>
                        <td class='text-center'>{% if acs_http.is_request %}<span class="badge">{{ acs_http.request_headers|length }} bytes</span>{% else %}N/A{% endif %}</td>
                        <td class='text-center'><span class="badge">{{ acs_http.body|length }} bytes</span></td>
                        <td>
                          {% if acs_http.rpc_response_to %}
                            {% include 'includes/small-details-button.html' with url=response_to_detail_url %}{{ acs_http.rpc_response_to.tag }}
                          {% else %}
                            N/A
                          {% endif %}
                        </td>
                        <td>
                          {% if acs_http.rpc_response %}
                            {% include 'includes/small-details-button.html' with url=rpc_response_detail_url %}{{ acs_http.rpc_response.tag }}
                          {% else %}
                            N/A
                          {% endif %}
                        </td>
                        <td>
                          {% if acs_http.queuejob %}
                            {% include 'includes/small-details-button.html' with url=queue_job_detail_url %}{{ acs_http.queuejob.tag }}
                          {% else %}
                            N/A
                          {% endif %}
                        </td>
                        <td>
                            {% include 'includes/details-button.html' with url=acs_http_detail_url %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            {% if is_paginated %}
                {% include 'includes/pagination-footer.html' %}
            {% endif %}
        {% else %}
            <p>No ACS HTTP Requests Found!</p>
        {% endif %}
{% include 'includes/collapsable-panel-footer.html' %}

acsadmin/templates/includes/acs_session_list_panel.html
{% load custom_template_filters %}
{% include 'includes/collapsable-panel-header.html' with name='AcsSessionList' headline=headline|default:"ACS Session List" %}
        {% if acs_session_list %}
            {% if not included %}
            <p>
              {% url 'acsadmin:acs_session_list' as all_sessions %}
              {% url 'acsadmin:acs_session_list_failed' as only_failed %}
              {% url 'acsadmin:acs_session_list_failed_verified' as only_failed_verified %}
              {% include 'includes/button.html' with url=all_sessions buttontext="Show All Sessions" %}
              {% include 'includes/button.html' with url=only_failed buttontext="Show Only Failed Sessions" %}
              {% include 'includes/button.html' with url=only_failed_verified buttontext="Show Only Dailed and IP Verified Sessions" %}
            </p>
            {% endif %}
            {% if is_paginated %}
                {% include 'includes/pagination-footer.html' %}
            {% endif %}
            <table class="table">
                <thead>
                    <tr>
                        <th>ACS Session</th>
                        <th>ACS Device</th>
                        <th>Client IP</th>
                        <th class='text-center'>Client IP Verified</th>
                        <th>Inform Event Codes</th>
                        <th>HTTP Request</th>
                        <th>HTTP Response</th>
                        <th>Start</th>
                        <th>Duration</th>
                        <th>Device Uptime</th>
                        <th>Last RPC Method</th>
                        <th>Bytes Received</th>
                        <th>Bytes Sent</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                {% for acs_session in acs_session_list %}
                    {% url 'acsadmin:acs_session_detail' pk=acs_session.id as acs_session_detail_url %}
                    {% url 'acsadmin:acs_device_detail' pk=acs_session.acs_device.id as acs_device_detail_url %}
                    <tr {% if not acs_session.session_result %} class="danger"{% endif %}>
                        <td>{% include 'includes/small-details-button.html' with url=acs_session_detail_url %}{{ acs_session.tag }}</td>
                        <td>{% include 'includes/small-details-button.html' with url=acs_device_detail_url %}{{ acs_session.acs_device.tag }}</td>
                        <td><a href="http://{{ acs_session.client_ip }}/" target="_blank">{{ acs_session.client_ip }}</a></td>
                        <td class='text-center'>{{ acs_session.client_ip_verified|truefalseicon|safe }}</td>
                        <td>{% for iec in acs_session.inform_eventcodes %}{{ iec }}<br>{% endfor %}</td>
                        <td><span class="badge">{{ acs_session.acs_http_requests.count }}</span></td>
                        <td><span class="badge">{{ acs_session.acs_http_responses.count }}</span></td>
                        <td>{{ acs_session.start }}</td>
                        <td>{{ acs_session.duration | pretty_timedelta }}</td>
                        <td>{{ acs_session.device_uptime | datetimerange_as_pretty_delta }}</td>
                        <td>{{ acs_session.get_latest_http_tx.soap_element_ns }}</td>
                        <td><span class="badge">{{ acs_session.bytes_in }} bytes</span></td>
                        <td><span class="badge">{{ acs_session.bytes_out }} bytes</span></td>
                        <td>
                            {% include 'includes/details-button.html' with url=acs_session_detail_url %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            {% if included %}
                {% url 'acsadmin:acsdevice_all_acs_sessions' pk=acs_device.id as all_acs_sessions_url %}
                {% include 'includes/button.html' with url=all_acs_sessions_url buttontext='Show All ACS Sessions for This ACS Device' %}
            {% endif %}
            {% if is_paginated %}
                {% include 'includes/pagination-footer.html' %}
            {% endif %}
        {% else %}
            <p>No ACS Sessions Found!</p>
        {% endif %}
{% include 'includes/collapsable-panel-footer.html' %}